# reshaping methods
import numpy as np
arr=np.arange(1,10)
print(arr)
reshaped = arr.reshape(3,3)
print("reshaped:\n",reshaped)
print(arr)
print(reshaped)
#print("ravel:",reshaped.ravel())
b=reshaped.ravel()
print("bb",b)
print(reshaped)
#print("flatten:",reshaped.flatten())
a=reshaped.flatten()
print("a",a)
print(reshaped)
arr.resize(3,3)
print("resize:\n",arr)
print(arr)